### ISSUE TITLE
Dio Exception while using the package

### ISSUE THREAD

**Issue by sa1dude23** [incrediblezayed/phone_pe_pg#1]
DioException [bad response]: The request returned an invalid status code of 400.

**Comment by incrediblezayed** [comment]
Hi, this is mostly because of invalid key, can you connect on discord if possible @sa1dude23

**Comment by sa1dude23** [comment]
Okay. Send me discord id

**Comment by sa1dude23** [comment]
The key is in Json file shared by phonepe. Still it is showing same thing

**Comment by incrediblezayed** [comment]
Hi, as per our discussion over call, the issue was not specifically in the package, so I'm closing this issue
