### ISSUE TITLE
success payment when user click on the back button 

### ISSUE THREAD

**Issue by ABHAYKACHA** [incrediblezayed/phone_pe_pg#2]
in this repository when i click on the back button it success the payment this is the main issue of this repository..

**Comment by incrediblezayed** [comment]
Already on this issue, will update probably tomorrow

**Comment by sagnik-sanyal** [comment]
Hi there, could you pls explain what is the issue about and why is this happening @incrediblezayed  ?

**Comment by incrediblezayed** [comment]
> Hi there, could you pls explain what is the issue about and why is this happening @incrediblezayed  ?

There was some issue with the api call flow, it's fixed but I haven't updated yet

**Comment by sagnik-sanyal** [comment]
Thanks for the info !. Btw when can we expect an update or if its a small change can you tell me where the change is ?

**Comment by incrediblezayed** [comment]
Updates @sagnik-sanyal , Please check v0.0.5

**Comment by rameshkec85** [comment]
Hi @incrediblezayed  Using v0.0.5 still getting the same issue. Any update on this.

**Comment by incrediblezayed** [comment]
@rameshkec85 Can you screenrecord or something if possible?

**Comment by incrediblezayed** [comment]
Closing the issues, opened for the long time without response
