### ISSUE TITLE
For UAT showing error "Prod URL should not be null if isUAT is false"

### ISSUE THREAD

**Issue by Sanaulla-0101** [incrediblezayed/phone_pe_pg#4]
**Error** 
════════ Exception caught by widgets library ═══════════════════════════════════
Prod URL should not be null if isUAT is false
'package:phone_pe_pg/src/src.dart':
src.dart:1
Failed assertion: line 20 pos 11: '!isUAT || (prodUrl != null && prodUrl.isNotEmpty)'

**My Code**

import 'dart:io';
import 'dart:math';
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:phone_pe_pg/phone_pe_pg.dart';

class PhonePePay extends StatefulWidget {
  const PhonePePay({Key? key}) : super(key: key);

  @override
  State<PhonePePay> createState() => _PhonePePayState();
}

class _PhonePePayState extends State<PhonePePay> {

  PhonePePg pePg = PhonePePg(
    isUAT: true, // true for UAT environment, false for production
    saltKey: "099eb0cd-02cf-4e2a-8aca-3e6c6aff0399",
    saltIndex: "1",
  );

  PaymentRequest _paymentRequest({String? merchantCallBackScheme}) {
    String generateRandomString(int len) {
      const chars =
          'AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz1234567890';
      Random rnd = Random();
      var s = String.fromCharCodes(Iterable.generate(
          len, (_) => chars.codeUnitAt(rnd.nextInt(chars.length))));
      return s;
    }

    PaymentRequest paymentRequest = PaymentRequest(
      amount: 1.00,
      callbackUrl: "https://www.xyx.com",
      deviceContext: DeviceContext.getDefaultDeviceContext(
          merchantCallBackScheme: merchantCallBackScheme),
      merchantId: "HASHJOBONLINE", 
      merchantTransactionId: generateRandomString(10).toUpperCase(),
      merchantUserId: generateRandomString(8).toUpperCase(),
      mobileNumber: "9049977349",
    );
    return paymentRequest;
  }

  PaymentRequest upipaymentRequest(UpiAppInfo e,
          {String? merchantCallBackScheme}) =>
      _paymentRequest(merchantCallBackScheme: merchantCallBackScheme).copyWith(
          paymentInstrument: UpiIntentPaymentInstrument(
        targetApp: Platform.isAndroid ? e.packageName! : e.iOSAppName!,
      ));

  PaymentRequest paypageRequestModel({String? merchantCallBackScheme}) =>
      _paymentRequest(merchantCallBackScheme: merchantCallBackScheme).copyWith(
          // redirectUrl: Secrets.redirectUrl,
          // redirectMode: 'GET',
          paymentInstrument: PayPagePaymentInstrument());

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Plugin example app'),
      ),
      body: FutureBuilder<List<UpiAppInfo>?>(
        future: PhonePePg.getUpiApps(iOSUpiApps: [
          UpiAppInfo(
            appName: "PhonePe",
            packageName: "ppe",
            appIcon: Uint8List(0),
            iOSAppName: "PHONEPE",
            iOSAppScheme: 'ppe',
          ),
          UpiAppInfo(
            appName: "Google Pay",
            packageName: "gpay",
            appIcon: Uint8List(0),
            iOSAppName: "GPAY",
            iOSAppScheme: 'gpay',
          ),
          UpiAppInfo(
            appName: "Paytm",
            packageName: "paytmmp",
            appIcon: Uint8List(0),
            iOSAppName: "PAYTM",
            iOSAppScheme: 'paytmmp',
          ),
          UpiAppInfo(
              appName: "PhonePe Simulator",
              packageName: "ppemerchantsdkv1",
              appIcon: Uint8List(0),
              iOSAppScheme: 'ppemerchantsdkv1',
              iOSAppName: "PHONEPE"),
          UpiAppInfo(
            appName: "PhonePe Simulator",
            packageName: "ppemerchantsdkv2",
            appIcon: Uint8List(0),
            iOSAppScheme: 'ppemerchantsdkv2',
            iOSAppName: "PHONEPE",
          ),
          UpiAppInfo(
            appName: "PhonePe Simulator",
            packageName: "ppemerchantsdkv3",
            iOSAppScheme: 'ppemerchantsdkv3',
            appIcon: Uint8List(0),
            iOSAppName: "PHONEPE",
          ),
        ]),
        builder: (context, snapshot) {
          if (snapshot.hasData && snapshot.data != null) {
            return ListView(children: [
              ...snapshot.data!
                  .map(
                    (e) => ListTile(
                      onTap: () async {
                        pePg
                            .startUpiTransaction(
                                paymentRequest: upipaymentRequest(e))
                            .then((response) {
                          if (response.status == UpiPaymentStatus.success) {
                            ScaffoldMessenger.of(context).showSnackBar(
                                const SnackBar(
                                    content:
                                        Text("Transaction Successful")));
                          } else if (response.status ==
                              UpiPaymentStatus.pending) {
                            ScaffoldMessenger.of(context).showSnackBar(
                                const SnackBar(
                                    content: Text("Transaction Pending")));
                          } else {
                            ScaffoldMessenger.of(context).showSnackBar(
                                const SnackBar(
                                    content: Text("Transaction Failed")));
                          }
                        }).catchError((e) {
                          ScaffoldMessenger.of(context).showSnackBar(
                              const SnackBar(
                                  content: Text("Transaction Failed")));
                        });
                      },
                      leading: Image.memory(
                        e.appIcon,
                        errorBuilder: (context, error, stackTrace) {
                          return const Icon(Icons.error);
                        },
                      ),
                      title: Text(e.appName),
                      subtitle: Text(e.packageName ?? e.iOSAppName!),
                    ),
                  )
                  .toList(),
              ListTile(
                title: const Text("Card/Net Banking"),
                onTap: () {
                  Navigator.push(
                      context,
                      MaterialPageRoute(
                          builder: (_) => pePg.startPayPageTransaction(
                                onPaymentComplete:
                                    (paymentResponse, paymentError) {
                                  Navigator.pop(context);
                                  if (paymentResponse != null &&
                                      paymentResponse.code ==
                                          PaymentStatus.success) {
                                    ScaffoldMessenger.of(context)
                                        .showSnackBar(const SnackBar(
                                            content: Text(
                                                "Transaction Successful")));
                                  } else {
                                    ScaffoldMessenger.of(context)
                                        .showSnackBar(const SnackBar(
                                            content: Text(
                                                "Transaction Failed")));
                                  }
                                },
                                paymentRequest: paypageRequestModel(),
                              )));
                },
              )
            ]);
          }
          return const Center(
            child: CircularProgressIndicator(),
          );
        },
      ),
    );
  }

}

I am picked this code from example section of pub.dev

**Comment by incrediblezayed** [comment]
Hey @Sanaulla-0101 Prod URL is the URL of your phonepe backend (You have to write a backend and deploy, I've given the example in the readme, please read that carefully), this url is needed when you've set `isUAT: false`

**Comment by Sanaulla-0101** [comment]
Yes sir, But as you can see code, I set IsUAT as true, and after that, it showed that error. 

PhonePePg pePg = PhonePePg(
    isUAT: true, 
    saltKey: "099eb0cd-02cf-4e2a-8aca-3e6c6aff0399",
    saltIndex: "1",
)

If isUAT set as true have requited prodUrl or Not. currently when given prodUrl that not showing error in isUAT : true

**Comment by incrediblezayed** [comment]
This is done and I'll push in the latest update @Sanaulla-0101
