### ISSUE TITLE
Phonepe flutter SDK

### ISSUE THREAD

**Issue by ghost** [incrediblezayed/phone_pe_pg#6]
Hi, I am implementing the flutter SDK my Simulator is working with SIM credentials but when I am trying in production with actual credentials it shows error Transaction Interrupted.

Can you help me

**Comment by incrediblezayed** [comment]
I think you need to get your server whitelisted @premiereessential

**Comment by ghost** [comment]
Phonepe team is asking for Static IP address and I am working on mobile application with firebase database.
How can I find the IP, help me out

**Comment by incrediblezayed** [comment]
@incrediblezayed You will have to get the static ip from where you have deployed the server code, sorry for late reply
